name: GitHub Pages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npx hexo algolia
        env:
          HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}
      - name: Override changes
        run: |
          cp -vrf override_changes/* node_modules/hexo-theme-icarus/
      - run: NODE_ENV=production npx hexo g
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
